slam_toolbox:
  ros__parameters:
    use_sim_time: True
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    max_laser_range: 3.5
    resolution: 0.05
    minimum_time_interval: 0.5
    transform_publish_period: 0.02