amcl:
  ros__parameters:
    use_sim_time: True
    min_particles: 500
    max_particles: 5000

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1

controller_server:
  ros__parameters:
    use_sim_time: True
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001